package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AuthGroupPermissions generated by hbm2java
 */
@Entity
@Table(name="auth_group_permissions"
    ,catalog="django_ois"
    , uniqueConstraints = @UniqueConstraint(columnNames={"group_id", "permission_id"}) 
)
public class AuthGroupPermissions  implements java.io.Serializable {


     private Integer id;
     private int groupId;
     private int permissionId;

    public AuthGroupPermissions() {
    }

    public AuthGroupPermissions(int groupId, int permissionId) {
       this.groupId = groupId;
       this.permissionId = permissionId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="group_id", nullable=false)
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }
    
    @Column(name="permission_id", nullable=false)
    public int getPermissionId() {
        return this.permissionId;
    }
    
    public void setPermissionId(int permissionId) {
        this.permissionId = permissionId;
    }




}


