package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DjangoAdminLog generated by hbm2java
 */
@Entity
@Table(name="django_admin_log"
    ,catalog="django_ois"
)
public class DjangoAdminLog  implements java.io.Serializable {


     private Integer id;
     private Date actionTime;
     private int userId;
     private Integer contentTypeId;
     private String objectId;
     private String objectRepr;
     private short actionFlag;
     private String changeMessage;

    public DjangoAdminLog() {
    }

	
    public DjangoAdminLog(Date actionTime, int userId, String objectRepr, short actionFlag, String changeMessage) {
        this.actionTime = actionTime;
        this.userId = userId;
        this.objectRepr = objectRepr;
        this.actionFlag = actionFlag;
        this.changeMessage = changeMessage;
    }
    public DjangoAdminLog(Date actionTime, int userId, Integer contentTypeId, String objectId, String objectRepr, short actionFlag, String changeMessage) {
       this.actionTime = actionTime;
       this.userId = userId;
       this.contentTypeId = contentTypeId;
       this.objectId = objectId;
       this.objectRepr = objectRepr;
       this.actionFlag = actionFlag;
       this.changeMessage = changeMessage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="action_time", nullable=false, length=19)
    public Date getActionTime() {
        return this.actionTime;
    }
    
    public void setActionTime(Date actionTime) {
        this.actionTime = actionTime;
    }
    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    @Column(name="content_type_id")
    public Integer getContentTypeId() {
        return this.contentTypeId;
    }
    
    public void setContentTypeId(Integer contentTypeId) {
        this.contentTypeId = contentTypeId;
    }
    
    @Column(name="object_id")
    public String getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }
    
    @Column(name="object_repr", nullable=false, length=200)
    public String getObjectRepr() {
        return this.objectRepr;
    }
    
    public void setObjectRepr(String objectRepr) {
        this.objectRepr = objectRepr;
    }
    
    @Column(name="action_flag", nullable=false)
    public short getActionFlag() {
        return this.actionFlag;
    }
    
    public void setActionFlag(short actionFlag) {
        this.actionFlag = actionFlag;
    }
    
    @Column(name="change_message", nullable=false)
    public String getChangeMessage() {
        return this.changeMessage;
    }
    
    public void setChangeMessage(String changeMessage) {
        this.changeMessage = changeMessage;
    }




}


