package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DjangoContentType generated by hbm2java
 */
@Entity
@Table(name="django_content_type"
    ,catalog="django_ois"
    , uniqueConstraints = @UniqueConstraint(columnNames={"app_label", "model"}) 
)
public class DjangoContentType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String appLabel;
     private String model;

    public DjangoContentType() {
    }

    public DjangoContentType(String name, String appLabel, String model) {
       this.name = name;
       this.appLabel = appLabel;
       this.model = model;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="app_label", nullable=false, length=100)
    public String getAppLabel() {
        return this.appLabel;
    }
    
    public void setAppLabel(String appLabel) {
        this.appLabel = appLabel;
    }
    
    @Column(name="model", nullable=false, length=100)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }




}


