package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShootingsOfficerweapon generated by hbm2java
 */
@Entity
@Table(name="shootings_officerweapon"
    ,catalog="django_ois"
)
public class ShootingsOfficerweapon  implements java.io.Serializable {


     private Integer id;
     private String weapon;

    public ShootingsOfficerweapon() {
    }

    public ShootingsOfficerweapon(String weapon) {
       this.weapon = weapon;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="weapon", nullable=false)
    public String getWeapon() {
        return this.weapon;
    }
    
    public void setWeapon(String weapon) {
        this.weapon = weapon;
    }




}


