package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShootingsLesslethalforce generated by hbm2java
 */
@Entity
@Table(name="shootings_lesslethalforce"
    ,catalog="django_ois"
)
public class ShootingsLesslethalforce  implements java.io.Serializable {


     private Integer id;
     private String lessLethalForce;

    public ShootingsLesslethalforce() {
    }

    public ShootingsLesslethalforce(String lessLethalForce) {
       this.lessLethalForce = lessLethalForce;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="less_lethal_force", nullable=false)
    public String getLessLethalForce() {
        return this.lessLethalForce;
    }
    
    public void setLessLethalForce(String lessLethalForce) {
        this.lessLethalForce = lessLethalForce;
    }




}


