package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShootingsAgency generated by hbm2java
 */
@Entity
@Table(name="shootings_agency"
    ,catalog="django_ois"
)
public class ShootingsAgency  implements java.io.Serializable {


     private Integer id;
     private String abbreviation;
     private String fullName;

    public ShootingsAgency() {
    }

    public ShootingsAgency(String abbreviation, String fullName) {
       this.abbreviation = abbreviation;
       this.fullName = fullName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="abbreviation", nullable=false)
    public String getAbbreviation() {
        return this.abbreviation;
    }
    
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }
    
    @Column(name="full_name", nullable=false)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }




}


