package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShootingsOfficer generated by hbm2java
 */
@Entity
@Table(name="shootings_officer"
    ,catalog="django_ois"
)
public class ShootingsOfficer  implements java.io.Serializable {


     private Integer id;
     private int incidentId;
     private String firstName;
     private String middleName;
     private String lastName;
     private Integer agencyId;
     private Integer ageAtShooting;
     private Integer shotsFired;
     private Date dob;
     private Integer raceId;
     private boolean stillOnForce;
     private Double yearsOnForce;
     private boolean inUniform;
     private boolean officerShot;
     private String partner;
     private String printImage;
     private String webImage;
     private String notes;
     private Integer rankId;
     private String gender;
     private boolean inPlainClothes;
     private Integer shotsFiredByPolice;
     private Integer height;
     private Integer weight;
     private String officerInjury;
     private Integer weapon1Id;
     private Integer weapon2Id;
     private Integer weapon3Id;
     private Integer weapon4Id;
     private Integer weapon5Id;
     private Integer weapon6Id;
     private Integer weapon7Id;
     private Integer weapon8Id;
     private Integer areaCommandId;
     private Integer officerlistId;
     private Integer photoId;

    public ShootingsOfficer() {
    }

	
    public ShootingsOfficer(int incidentId, String firstName, String middleName, String lastName, boolean stillOnForce, boolean inUniform, boolean officerShot, String partner, String notes, String gender, boolean inPlainClothes, String officerInjury) {
        this.incidentId = incidentId;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.stillOnForce = stillOnForce;
        this.inUniform = inUniform;
        this.officerShot = officerShot;
        this.partner = partner;
        this.notes = notes;
        this.gender = gender;
        this.inPlainClothes = inPlainClothes;
        this.officerInjury = officerInjury;
    }
    public ShootingsOfficer(int incidentId, String firstName, String middleName, String lastName, Integer agencyId, Integer ageAtShooting, Integer shotsFired, Date dob, Integer raceId, boolean stillOnForce, Double yearsOnForce, boolean inUniform, boolean officerShot, String partner, String printImage, String webImage, String notes, Integer rankId, String gender, boolean inPlainClothes, Integer shotsFiredByPolice, Integer height, Integer weight, String officerInjury, Integer weapon1Id, Integer weapon2Id, Integer weapon3Id, Integer weapon4Id, Integer weapon5Id, Integer weapon6Id, Integer weapon7Id, Integer weapon8Id, Integer areaCommandId, Integer officerlistId, Integer photoId) {
       this.incidentId = incidentId;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.agencyId = agencyId;
       this.ageAtShooting = ageAtShooting;
       this.shotsFired = shotsFired;
       this.dob = dob;
       this.raceId = raceId;
       this.stillOnForce = stillOnForce;
       this.yearsOnForce = yearsOnForce;
       this.inUniform = inUniform;
       this.officerShot = officerShot;
       this.partner = partner;
       this.printImage = printImage;
       this.webImage = webImage;
       this.notes = notes;
       this.rankId = rankId;
       this.gender = gender;
       this.inPlainClothes = inPlainClothes;
       this.shotsFiredByPolice = shotsFiredByPolice;
       this.height = height;
       this.weight = weight;
       this.officerInjury = officerInjury;
       this.weapon1Id = weapon1Id;
       this.weapon2Id = weapon2Id;
       this.weapon3Id = weapon3Id;
       this.weapon4Id = weapon4Id;
       this.weapon5Id = weapon5Id;
       this.weapon6Id = weapon6Id;
       this.weapon7Id = weapon7Id;
       this.weapon8Id = weapon8Id;
       this.areaCommandId = areaCommandId;
       this.officerlistId = officerlistId;
       this.photoId = photoId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="incident_id", nullable=false)
    public int getIncidentId() {
        return this.incidentId;
    }
    
    public void setIncidentId(int incidentId) {
        this.incidentId = incidentId;
    }
    
    @Column(name="first_name", nullable=false, length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="middle_name", nullable=false, length=100)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    
    @Column(name="last_name", nullable=false, length=100)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="agency_id")
    public Integer getAgencyId() {
        return this.agencyId;
    }
    
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }
    
    @Column(name="age_at_shooting")
    public Integer getAgeAtShooting() {
        return this.ageAtShooting;
    }
    
    public void setAgeAtShooting(Integer ageAtShooting) {
        this.ageAtShooting = ageAtShooting;
    }
    
    @Column(name="shots_fired")
    public Integer getShotsFired() {
        return this.shotsFired;
    }
    
    public void setShotsFired(Integer shotsFired) {
        this.shotsFired = shotsFired;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dob", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    
    @Column(name="race_id")
    public Integer getRaceId() {
        return this.raceId;
    }
    
    public void setRaceId(Integer raceId) {
        this.raceId = raceId;
    }
    
    @Column(name="still_on_force", nullable=false)
    public boolean isStillOnForce() {
        return this.stillOnForce;
    }
    
    public void setStillOnForce(boolean stillOnForce) {
        this.stillOnForce = stillOnForce;
    }
    
    @Column(name="years_on_force", precision=22, scale=0)
    public Double getYearsOnForce() {
        return this.yearsOnForce;
    }
    
    public void setYearsOnForce(Double yearsOnForce) {
        this.yearsOnForce = yearsOnForce;
    }
    
    @Column(name="in_uniform", nullable=false)
    public boolean isInUniform() {
        return this.inUniform;
    }
    
    public void setInUniform(boolean inUniform) {
        this.inUniform = inUniform;
    }
    
    @Column(name="officer_shot", nullable=false)
    public boolean isOfficerShot() {
        return this.officerShot;
    }
    
    public void setOfficerShot(boolean officerShot) {
        this.officerShot = officerShot;
    }
    
    @Column(name="partner", nullable=false)
    public String getPartner() {
        return this.partner;
    }
    
    public void setPartner(String partner) {
        this.partner = partner;
    }
    
    @Column(name="print_image")
    public String getPrintImage() {
        return this.printImage;
    }
    
    public void setPrintImage(String printImage) {
        this.printImage = printImage;
    }
    
    @Column(name="web_image")
    public String getWebImage() {
        return this.webImage;
    }
    
    public void setWebImage(String webImage) {
        this.webImage = webImage;
    }
    
    @Column(name="notes", nullable=false)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    @Column(name="rank_id")
    public Integer getRankId() {
        return this.rankId;
    }
    
    public void setRankId(Integer rankId) {
        this.rankId = rankId;
    }
    
    @Column(name="gender", nullable=false, length=1)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    
    @Column(name="in_plain_clothes", nullable=false)
    public boolean isInPlainClothes() {
        return this.inPlainClothes;
    }
    
    public void setInPlainClothes(boolean inPlainClothes) {
        this.inPlainClothes = inPlainClothes;
    }
    
    @Column(name="shots_fired_by_police")
    public Integer getShotsFiredByPolice() {
        return this.shotsFiredByPolice;
    }
    
    public void setShotsFiredByPolice(Integer shotsFiredByPolice) {
        this.shotsFiredByPolice = shotsFiredByPolice;
    }
    
    @Column(name="height")
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }
    
    @Column(name="weight")
    public Integer getWeight() {
        return this.weight;
    }
    
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
    
    @Column(name="officer_injury", nullable=false, length=1)
    public String getOfficerInjury() {
        return this.officerInjury;
    }
    
    public void setOfficerInjury(String officerInjury) {
        this.officerInjury = officerInjury;
    }
    
    @Column(name="weapon1_id")
    public Integer getWeapon1Id() {
        return this.weapon1Id;
    }
    
    public void setWeapon1Id(Integer weapon1Id) {
        this.weapon1Id = weapon1Id;
    }
    
    @Column(name="weapon2_id")
    public Integer getWeapon2Id() {
        return this.weapon2Id;
    }
    
    public void setWeapon2Id(Integer weapon2Id) {
        this.weapon2Id = weapon2Id;
    }
    
    @Column(name="weapon3_id")
    public Integer getWeapon3Id() {
        return this.weapon3Id;
    }
    
    public void setWeapon3Id(Integer weapon3Id) {
        this.weapon3Id = weapon3Id;
    }
    
    @Column(name="weapon4_id")
    public Integer getWeapon4Id() {
        return this.weapon4Id;
    }
    
    public void setWeapon4Id(Integer weapon4Id) {
        this.weapon4Id = weapon4Id;
    }
    
    @Column(name="weapon5_id")
    public Integer getWeapon5Id() {
        return this.weapon5Id;
    }
    
    public void setWeapon5Id(Integer weapon5Id) {
        this.weapon5Id = weapon5Id;
    }
    
    @Column(name="weapon6_id")
    public Integer getWeapon6Id() {
        return this.weapon6Id;
    }
    
    public void setWeapon6Id(Integer weapon6Id) {
        this.weapon6Id = weapon6Id;
    }
    
    @Column(name="weapon7_id")
    public Integer getWeapon7Id() {
        return this.weapon7Id;
    }
    
    public void setWeapon7Id(Integer weapon7Id) {
        this.weapon7Id = weapon7Id;
    }
    
    @Column(name="weapon8_id")
    public Integer getWeapon8Id() {
        return this.weapon8Id;
    }
    
    public void setWeapon8Id(Integer weapon8Id) {
        this.weapon8Id = weapon8Id;
    }
    
    @Column(name="area_command_id")
    public Integer getAreaCommandId() {
        return this.areaCommandId;
    }
    
    public void setAreaCommandId(Integer areaCommandId) {
        this.areaCommandId = areaCommandId;
    }
    
    @Column(name="officerlist_id")
    public Integer getOfficerlistId() {
        return this.officerlistId;
    }
    
    public void setOfficerlistId(Integer officerlistId) {
        this.officerlistId = officerlistId;
    }
    
    @Column(name="photo_id")
    public Integer getPhotoId() {
        return this.photoId;
    }
    
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }




}


