package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShootingsCalltype generated by hbm2java
 */
@Entity
@Table(name="shootings_calltype"
    ,catalog="django_ois"
)
public class ShootingsCalltype  implements java.io.Serializable {


     private Integer id;
     private String callType;

    public ShootingsCalltype() {
    }

    public ShootingsCalltype(String callType) {
       this.callType = callType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="call_type", nullable=false, length=64)
    public String getCallType() {
        return this.callType;
    }
    
    public void setCallType(String callType) {
        this.callType = callType;
    }




}


