package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShootingsSuspect generated by hbm2java
 */
@Entity
@Table(name="shootings_suspect"
    ,catalog="django_ois"
)
public class ShootingsSuspect  implements java.io.Serializable {


     private Integer id;
     private int incidentId;
     private String firstName;
     private String middleName;
     private String lastName;
     private Integer age;
     private Integer raceId;
     private String address;
     private String city;
     private String state;
     private boolean assaultedOthers;
     private boolean suicidal;
     private boolean mentallyIll;
     private boolean criminalBackground;
     private boolean violentCriminalHistory;
     private String printImage;
     private String webImage;
     private boolean stolenGun;
     private Integer armed1Id;
     private Integer armed2Id;
     private Integer armed3Id;
     private Integer armed4Id;
     private Integer tox1Id;
     private Integer tox2Id;
     private Integer tox3Id;
     private Integer tox4Id;
     private String crime1;
     private String crime2;
     private String crime3;
     private String crime4;
     private String notes;
     private String gender;
     private String criminalHistory;
     private String militaryOrPoliceExperience;
     private String whereShot1;
     private String whereShot2;
     private String whereShot3;
     private String whereShot4;
     private String whereShot5;
     private String whereShot6;
     private Integer suspectCrime1Id;
     private Integer suspectCrime2Id;
     private Integer suspectCrime3Id;
     private Integer suspectCrime4Id;
     private Integer suspectlistId;
     private Integer photoId;

    public ShootingsSuspect() {
    }

	
    public ShootingsSuspect(int incidentId, String firstName, String middleName, String lastName, String address, String city, String state, boolean assaultedOthers, boolean suicidal, boolean mentallyIll, boolean criminalBackground, boolean violentCriminalHistory, boolean stolenGun, String crime1, String crime2, String crime3, String crime4, String notes, String gender, String criminalHistory, String militaryOrPoliceExperience, String whereShot1, String whereShot2, String whereShot3, String whereShot4, String whereShot5, String whereShot6) {
        this.incidentId = incidentId;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.address = address;
        this.city = city;
        this.state = state;
        this.assaultedOthers = assaultedOthers;
        this.suicidal = suicidal;
        this.mentallyIll = mentallyIll;
        this.criminalBackground = criminalBackground;
        this.violentCriminalHistory = violentCriminalHistory;
        this.stolenGun = stolenGun;
        this.crime1 = crime1;
        this.crime2 = crime2;
        this.crime3 = crime3;
        this.crime4 = crime4;
        this.notes = notes;
        this.gender = gender;
        this.criminalHistory = criminalHistory;
        this.militaryOrPoliceExperience = militaryOrPoliceExperience;
        this.whereShot1 = whereShot1;
        this.whereShot2 = whereShot2;
        this.whereShot3 = whereShot3;
        this.whereShot4 = whereShot4;
        this.whereShot5 = whereShot5;
        this.whereShot6 = whereShot6;
    }
    public ShootingsSuspect(int incidentId, String firstName, String middleName, String lastName, Integer age, Integer raceId, String address, String city, String state, boolean assaultedOthers, boolean suicidal, boolean mentallyIll, boolean criminalBackground, boolean violentCriminalHistory, String printImage, String webImage, boolean stolenGun, Integer armed1Id, Integer armed2Id, Integer armed3Id, Integer armed4Id, Integer tox1Id, Integer tox2Id, Integer tox3Id, Integer tox4Id, String crime1, String crime2, String crime3, String crime4, String notes, String gender, String criminalHistory, String militaryOrPoliceExperience, String whereShot1, String whereShot2, String whereShot3, String whereShot4, String whereShot5, String whereShot6, Integer suspectCrime1Id, Integer suspectCrime2Id, Integer suspectCrime3Id, Integer suspectCrime4Id, Integer suspectlistId, Integer photoId) {
       this.incidentId = incidentId;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.age = age;
       this.raceId = raceId;
       this.address = address;
       this.city = city;
       this.state = state;
       this.assaultedOthers = assaultedOthers;
       this.suicidal = suicidal;
       this.mentallyIll = mentallyIll;
       this.criminalBackground = criminalBackground;
       this.violentCriminalHistory = violentCriminalHistory;
       this.printImage = printImage;
       this.webImage = webImage;
       this.stolenGun = stolenGun;
       this.armed1Id = armed1Id;
       this.armed2Id = armed2Id;
       this.armed3Id = armed3Id;
       this.armed4Id = armed4Id;
       this.tox1Id = tox1Id;
       this.tox2Id = tox2Id;
       this.tox3Id = tox3Id;
       this.tox4Id = tox4Id;
       this.crime1 = crime1;
       this.crime2 = crime2;
       this.crime3 = crime3;
       this.crime4 = crime4;
       this.notes = notes;
       this.gender = gender;
       this.criminalHistory = criminalHistory;
       this.militaryOrPoliceExperience = militaryOrPoliceExperience;
       this.whereShot1 = whereShot1;
       this.whereShot2 = whereShot2;
       this.whereShot3 = whereShot3;
       this.whereShot4 = whereShot4;
       this.whereShot5 = whereShot5;
       this.whereShot6 = whereShot6;
       this.suspectCrime1Id = suspectCrime1Id;
       this.suspectCrime2Id = suspectCrime2Id;
       this.suspectCrime3Id = suspectCrime3Id;
       this.suspectCrime4Id = suspectCrime4Id;
       this.suspectlistId = suspectlistId;
       this.photoId = photoId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="incident_id", nullable=false)
    public int getIncidentId() {
        return this.incidentId;
    }
    
    public void setIncidentId(int incidentId) {
        this.incidentId = incidentId;
    }
    
    @Column(name="first_name", nullable=false, length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="middle_name", nullable=false, length=100)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    
    @Column(name="last_name", nullable=false, length=100)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="age")
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    
    @Column(name="race_id")
    public Integer getRaceId() {
        return this.raceId;
    }
    
    public void setRaceId(Integer raceId) {
        this.raceId = raceId;
    }
    
    @Column(name="address", nullable=false)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="city", nullable=false)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="state", nullable=false, length=2)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="assaulted_others", nullable=false)
    public boolean isAssaultedOthers() {
        return this.assaultedOthers;
    }
    
    public void setAssaultedOthers(boolean assaultedOthers) {
        this.assaultedOthers = assaultedOthers;
    }
    
    @Column(name="suicidal", nullable=false)
    public boolean isSuicidal() {
        return this.suicidal;
    }
    
    public void setSuicidal(boolean suicidal) {
        this.suicidal = suicidal;
    }
    
    @Column(name="mentally_ill", nullable=false)
    public boolean isMentallyIll() {
        return this.mentallyIll;
    }
    
    public void setMentallyIll(boolean mentallyIll) {
        this.mentallyIll = mentallyIll;
    }
    
    @Column(name="criminal_background", nullable=false)
    public boolean isCriminalBackground() {
        return this.criminalBackground;
    }
    
    public void setCriminalBackground(boolean criminalBackground) {
        this.criminalBackground = criminalBackground;
    }
    
    @Column(name="violent_criminal_history", nullable=false)
    public boolean isViolentCriminalHistory() {
        return this.violentCriminalHistory;
    }
    
    public void setViolentCriminalHistory(boolean violentCriminalHistory) {
        this.violentCriminalHistory = violentCriminalHistory;
    }
    
    @Column(name="print_image")
    public String getPrintImage() {
        return this.printImage;
    }
    
    public void setPrintImage(String printImage) {
        this.printImage = printImage;
    }
    
    @Column(name="web_image")
    public String getWebImage() {
        return this.webImage;
    }
    
    public void setWebImage(String webImage) {
        this.webImage = webImage;
    }
    
    @Column(name="stolen_gun", nullable=false)
    public boolean isStolenGun() {
        return this.stolenGun;
    }
    
    public void setStolenGun(boolean stolenGun) {
        this.stolenGun = stolenGun;
    }
    
    @Column(name="armed1_id")
    public Integer getArmed1Id() {
        return this.armed1Id;
    }
    
    public void setArmed1Id(Integer armed1Id) {
        this.armed1Id = armed1Id;
    }
    
    @Column(name="armed2_id")
    public Integer getArmed2Id() {
        return this.armed2Id;
    }
    
    public void setArmed2Id(Integer armed2Id) {
        this.armed2Id = armed2Id;
    }
    
    @Column(name="armed3_id")
    public Integer getArmed3Id() {
        return this.armed3Id;
    }
    
    public void setArmed3Id(Integer armed3Id) {
        this.armed3Id = armed3Id;
    }
    
    @Column(name="armed4_id")
    public Integer getArmed4Id() {
        return this.armed4Id;
    }
    
    public void setArmed4Id(Integer armed4Id) {
        this.armed4Id = armed4Id;
    }
    
    @Column(name="tox1_id")
    public Integer getTox1Id() {
        return this.tox1Id;
    }
    
    public void setTox1Id(Integer tox1Id) {
        this.tox1Id = tox1Id;
    }
    
    @Column(name="tox2_id")
    public Integer getTox2Id() {
        return this.tox2Id;
    }
    
    public void setTox2Id(Integer tox2Id) {
        this.tox2Id = tox2Id;
    }
    
    @Column(name="tox3_id")
    public Integer getTox3Id() {
        return this.tox3Id;
    }
    
    public void setTox3Id(Integer tox3Id) {
        this.tox3Id = tox3Id;
    }
    
    @Column(name="tox4_id")
    public Integer getTox4Id() {
        return this.tox4Id;
    }
    
    public void setTox4Id(Integer tox4Id) {
        this.tox4Id = tox4Id;
    }
    
    @Column(name="crime1", nullable=false)
    public String getCrime1() {
        return this.crime1;
    }
    
    public void setCrime1(String crime1) {
        this.crime1 = crime1;
    }
    
    @Column(name="crime2", nullable=false)
    public String getCrime2() {
        return this.crime2;
    }
    
    public void setCrime2(String crime2) {
        this.crime2 = crime2;
    }
    
    @Column(name="crime3", nullable=false)
    public String getCrime3() {
        return this.crime3;
    }
    
    public void setCrime3(String crime3) {
        this.crime3 = crime3;
    }
    
    @Column(name="crime4", nullable=false)
    public String getCrime4() {
        return this.crime4;
    }
    
    public void setCrime4(String crime4) {
        this.crime4 = crime4;
    }
    
    @Column(name="notes", nullable=false)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    @Column(name="gender", nullable=false, length=1)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    
    @Column(name="criminal_history", nullable=false, length=1)
    public String getCriminalHistory() {
        return this.criminalHistory;
    }
    
    public void setCriminalHistory(String criminalHistory) {
        this.criminalHistory = criminalHistory;
    }
    
    @Column(name="military_or_police_experience", nullable=false, length=1)
    public String getMilitaryOrPoliceExperience() {
        return this.militaryOrPoliceExperience;
    }
    
    public void setMilitaryOrPoliceExperience(String militaryOrPoliceExperience) {
        this.militaryOrPoliceExperience = militaryOrPoliceExperience;
    }
    
    @Column(name="where_shot1", nullable=false)
    public String getWhereShot1() {
        return this.whereShot1;
    }
    
    public void setWhereShot1(String whereShot1) {
        this.whereShot1 = whereShot1;
    }
    
    @Column(name="where_shot2", nullable=false)
    public String getWhereShot2() {
        return this.whereShot2;
    }
    
    public void setWhereShot2(String whereShot2) {
        this.whereShot2 = whereShot2;
    }
    
    @Column(name="where_shot3", nullable=false)
    public String getWhereShot3() {
        return this.whereShot3;
    }
    
    public void setWhereShot3(String whereShot3) {
        this.whereShot3 = whereShot3;
    }
    
    @Column(name="where_shot4", nullable=false)
    public String getWhereShot4() {
        return this.whereShot4;
    }
    
    public void setWhereShot4(String whereShot4) {
        this.whereShot4 = whereShot4;
    }
    
    @Column(name="where_shot5", nullable=false)
    public String getWhereShot5() {
        return this.whereShot5;
    }
    
    public void setWhereShot5(String whereShot5) {
        this.whereShot5 = whereShot5;
    }
    
    @Column(name="where_shot6", nullable=false)
    public String getWhereShot6() {
        return this.whereShot6;
    }
    
    public void setWhereShot6(String whereShot6) {
        this.whereShot6 = whereShot6;
    }
    
    @Column(name="suspect_crime1_id")
    public Integer getSuspectCrime1Id() {
        return this.suspectCrime1Id;
    }
    
    public void setSuspectCrime1Id(Integer suspectCrime1Id) {
        this.suspectCrime1Id = suspectCrime1Id;
    }
    
    @Column(name="suspect_crime2_id")
    public Integer getSuspectCrime2Id() {
        return this.suspectCrime2Id;
    }
    
    public void setSuspectCrime2Id(Integer suspectCrime2Id) {
        this.suspectCrime2Id = suspectCrime2Id;
    }
    
    @Column(name="suspect_crime3_id")
    public Integer getSuspectCrime3Id() {
        return this.suspectCrime3Id;
    }
    
    public void setSuspectCrime3Id(Integer suspectCrime3Id) {
        this.suspectCrime3Id = suspectCrime3Id;
    }
    
    @Column(name="suspect_crime4_id")
    public Integer getSuspectCrime4Id() {
        return this.suspectCrime4Id;
    }
    
    public void setSuspectCrime4Id(Integer suspectCrime4Id) {
        this.suspectCrime4Id = suspectCrime4Id;
    }
    
    @Column(name="suspectlist_id")
    public Integer getSuspectlistId() {
        return this.suspectlistId;
    }
    
    public void setSuspectlistId(Integer suspectlistId) {
        this.suspectlistId = suspectlistId;
    }
    
    @Column(name="photo_id")
    public Integer getPhotoId() {
        return this.photoId;
    }
    
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }




}


