package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShootingsOfficeragency generated by hbm2java
 */
@Entity
@Table(name="shootings_officeragency"
    ,catalog="django_ois"
)
public class ShootingsOfficeragency  implements java.io.Serializable {


     private Integer id;
     private int officerlistId;
     private Integer agencyId;
     private String badge;
     private Date hiredDate;
     private boolean stillOnForce;

    public ShootingsOfficeragency() {
    }

	
    public ShootingsOfficeragency(int officerlistId, String badge, boolean stillOnForce) {
        this.officerlistId = officerlistId;
        this.badge = badge;
        this.stillOnForce = stillOnForce;
    }
    public ShootingsOfficeragency(int officerlistId, Integer agencyId, String badge, Date hiredDate, boolean stillOnForce) {
       this.officerlistId = officerlistId;
       this.agencyId = agencyId;
       this.badge = badge;
       this.hiredDate = hiredDate;
       this.stillOnForce = stillOnForce;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="officerlist_id", nullable=false)
    public int getOfficerlistId() {
        return this.officerlistId;
    }
    
    public void setOfficerlistId(int officerlistId) {
        this.officerlistId = officerlistId;
    }
    
    @Column(name="agency_id")
    public Integer getAgencyId() {
        return this.agencyId;
    }
    
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }
    
    @Column(name="badge", nullable=false, length=64)
    public String getBadge() {
        return this.badge;
    }
    
    public void setBadge(String badge) {
        this.badge = badge;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="hired_date", length=10)
    public Date getHiredDate() {
        return this.hiredDate;
    }
    
    public void setHiredDate(Date hiredDate) {
        this.hiredDate = hiredDate;
    }
    
    @Column(name="still_on_force", nullable=false)
    public boolean isStillOnForce() {
        return this.stillOnForce;
    }
    
    public void setStillOnForce(boolean stillOnForce) {
        this.stillOnForce = stillOnForce;
    }




}


