package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShootingsPolicereport generated by hbm2java
 */
@Entity
@Table(name="shootings_policereport"
    ,catalog="django_ois"
)
public class ShootingsPolicereport  implements java.io.Serializable {


     private Integer id;
     private int incidentId;
     private String policeReportId;

    public ShootingsPolicereport() {
    }

    public ShootingsPolicereport(int incidentId, String policeReportId) {
       this.incidentId = incidentId;
       this.policeReportId = policeReportId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="incident_id", nullable=false)
    public int getIncidentId() {
        return this.incidentId;
    }
    
    public void setIncidentId(int incidentId) {
        this.incidentId = incidentId;
    }
    
    @Column(name="police_report_id", nullable=false, length=50)
    public String getPoliceReportId() {
        return this.policeReportId;
    }
    
    public void setPoliceReportId(String policeReportId) {
        this.policeReportId = policeReportId;
    }




}


