package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShootingsStory generated by hbm2java
 */
@Entity
@Table(name="shootings_story"
    ,catalog="django_ois"
)
public class ShootingsStory  implements java.io.Serializable {


     private Integer id;
     private int incidentId;
     private String storyId;
     private String storyUrl;
     private String storyTitle;

    public ShootingsStory() {
    }

	
    public ShootingsStory(int incidentId, String storyId) {
        this.incidentId = incidentId;
        this.storyId = storyId;
    }
    public ShootingsStory(int incidentId, String storyId, String storyUrl, String storyTitle) {
       this.incidentId = incidentId;
       this.storyId = storyId;
       this.storyUrl = storyUrl;
       this.storyTitle = storyTitle;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="incident_id", nullable=false)
    public int getIncidentId() {
        return this.incidentId;
    }
    
    public void setIncidentId(int incidentId) {
        this.incidentId = incidentId;
    }
    
    @Column(name="story_id", nullable=false, length=50)
    public String getStoryId() {
        return this.storyId;
    }
    
    public void setStoryId(String storyId) {
        this.storyId = storyId;
    }
    
    @Column(name="story_url")
    public String getStoryUrl() {
        return this.storyUrl;
    }
    
    public void setStoryUrl(String storyUrl) {
        this.storyUrl = storyUrl;
    }
    
    @Column(name="story_title")
    public String getStoryTitle() {
        return this.storyTitle;
    }
    
    public void setStoryTitle(String storyTitle) {
        this.storyTitle = storyTitle;
    }




}


