package com.photoservice.entity;
// Generated Mar 23, 2012 2:14:48 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Assignments generated by hbm2java
 */
@Entity
@Table(name="Assignments"
    ,catalog="photo"
)
public class Assignments  implements java.io.Serializable {


     private int id;
     private String assignmentType;
     private Date created;
     private Date assignmentDue;
     private Date runDate;
     private String address;
     private String city;
     private Boolean canBeRescheduled;
     private Boolean reporterThere;
     private Boolean shotsNeeded;
     private String photographerName;
     private String photographerPhone;
     private String photoNotes;
     private String reporterName;
     private String reporterPhone;
     private String editorName;
     private String editorPhone;
     private String contactName;
     private String contactPhone;
     private String storyIdea;
     private String notes;
     private String sectionName;
     private String photoLocation;
     private String photoType;
     private Date eventDate;
     private String requestor;

    public Assignments() {
    }

	
    public Assignments(int id) {
        this.id = id;
    }
    public Assignments(int id, String assignmentType, Date created, Date assignmentDue, Date runDate, String address, String city, Boolean canBeRescheduled, Boolean reporterThere, Boolean shotsNeeded, String photographerName, String photographerPhone, String photoNotes, String reporterName, String reporterPhone, String editorName, String editorPhone, String contactName, String contactPhone, String storyIdea, String notes, String sectionName, String photoLocation, String photoType, Date eventDate, String requestor) {
       this.id = id;
       this.assignmentType = assignmentType;
       this.created = created;
       this.assignmentDue = assignmentDue;
       this.runDate = runDate;
       this.address = address;
       this.city = city;
       this.canBeRescheduled = canBeRescheduled;
       this.reporterThere = reporterThere;
       this.shotsNeeded = shotsNeeded;
       this.photographerName = photographerName;
       this.photographerPhone = photographerPhone;
       this.photoNotes = photoNotes;
       this.reporterName = reporterName;
       this.reporterPhone = reporterPhone;
       this.editorName = editorName;
       this.editorPhone = editorPhone;
       this.contactName = contactName;
       this.contactPhone = contactPhone;
       this.storyIdea = storyIdea;
       this.notes = notes;
       this.sectionName = sectionName;
       this.photoLocation = photoLocation;
       this.photoType = photoType;
       this.eventDate = eventDate;
       this.requestor = requestor;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="assignmentType", length=10)
    public String getAssignmentType() {
        return this.assignmentType;
    }
    
    public void setAssignmentType(String assignmentType) {
        this.assignmentType = assignmentType;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="created", length=10)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="assignmentDue", length=10)
    public Date getAssignmentDue() {
        return this.assignmentDue;
    }
    
    public void setAssignmentDue(Date assignmentDue) {
        this.assignmentDue = assignmentDue;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="runDate", length=10)
    public Date getRunDate() {
        return this.runDate;
    }
    
    public void setRunDate(Date runDate) {
        this.runDate = runDate;
    }
    
    @Column(name="address", length=300)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="city", length=300)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="canBeRescheduled")
    public Boolean getCanBeRescheduled() {
        return this.canBeRescheduled;
    }
    
    public void setCanBeRescheduled(Boolean canBeRescheduled) {
        this.canBeRescheduled = canBeRescheduled;
    }
    
    @Column(name="reporterThere")
    public Boolean getReporterThere() {
        return this.reporterThere;
    }
    
    public void setReporterThere(Boolean reporterThere) {
        this.reporterThere = reporterThere;
    }
    
    @Column(name="shotsNeeded")
    public Boolean getShotsNeeded() {
        return this.shotsNeeded;
    }
    
    public void setShotsNeeded(Boolean shotsNeeded) {
        this.shotsNeeded = shotsNeeded;
    }
    
    @Column(name="photographerName", length=300)
    public String getPhotographerName() {
        return this.photographerName;
    }
    
    public void setPhotographerName(String photographerName) {
        this.photographerName = photographerName;
    }
    
    @Column(name="photographerPhone", length=10)
    public String getPhotographerPhone() {
        return this.photographerPhone;
    }
    
    public void setPhotographerPhone(String photographerPhone) {
        this.photographerPhone = photographerPhone;
    }
    
    @Column(name="photoNotes", length=1000)
    public String getPhotoNotes() {
        return this.photoNotes;
    }
    
    public void setPhotoNotes(String photoNotes) {
        this.photoNotes = photoNotes;
    }
    
    @Column(name="reporterName", length=300)
    public String getReporterName() {
        return this.reporterName;
    }
    
    public void setReporterName(String reporterName) {
        this.reporterName = reporterName;
    }
    
    @Column(name="reporterPhone", length=10)
    public String getReporterPhone() {
        return this.reporterPhone;
    }
    
    public void setReporterPhone(String reporterPhone) {
        this.reporterPhone = reporterPhone;
    }
    
    @Column(name="editorName", length=300)
    public String getEditorName() {
        return this.editorName;
    }
    
    public void setEditorName(String editorName) {
        this.editorName = editorName;
    }
    
    @Column(name="editorPhone", length=10)
    public String getEditorPhone() {
        return this.editorPhone;
    }
    
    public void setEditorPhone(String editorPhone) {
        this.editorPhone = editorPhone;
    }
    
    @Column(name="contactName", length=300)
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    
    @Column(name="contactPhone", length=10)
    public String getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }
    
    @Column(name="storyIdea", length=1000)
    public String getStoryIdea() {
        return this.storyIdea;
    }
    
    public void setStoryIdea(String storyIdea) {
        this.storyIdea = storyIdea;
    }
    
    @Column(name="notes", length=1000)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    @Column(name="sectionName", length=300)
    public String getSectionName() {
        return this.sectionName;
    }
    
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }
    
    @Column(name="photoLocation", length=1000)
    public String getPhotoLocation() {
        return this.photoLocation;
    }
    
    public void setPhotoLocation(String photoLocation) {
        this.photoLocation = photoLocation;
    }
    
    @Column(name="photoType", length=10)
    public String getPhotoType() {
        return this.photoType;
    }
    
    public void setPhotoType(String photoType) {
        this.photoType = photoType;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="eventDate", length=10)
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }
    
    @Column(name="requestor", length=1000)
    public String getRequestor() {
        return this.requestor;
    }
    
    public void setRequestor(String requestor) {
        this.requestor = requestor;
    }




}


