package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AuthUserUserPermissions generated by hbm2java
 */
@Entity
@Table(name="auth_user_user_permissions"
    ,catalog="django_ois"
    , uniqueConstraints = @UniqueConstraint(columnNames={"user_id", "permission_id"}) 
)
public class AuthUserUserPermissions  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private int permissionId;

    public AuthUserUserPermissions() {
    }

    public AuthUserUserPermissions(int userId, int permissionId) {
       this.userId = userId;
       this.permissionId = permissionId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    @Column(name="permission_id", nullable=false)
    public int getPermissionId() {
        return this.permissionId;
    }
    
    public void setPermissionId(int permissionId) {
        this.permissionId = permissionId;
    }




}


