package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DjangoSession generated by hbm2java
 */
@Entity
@Table(name="django_session"
    ,catalog="django_ois"
)
public class DjangoSession  implements java.io.Serializable {


     private String sessionKey;
     private String sessionData;
     private Date expireDate;

    public DjangoSession() {
    }

    public DjangoSession(String sessionKey, String sessionData, Date expireDate) {
       this.sessionKey = sessionKey;
       this.sessionData = sessionData;
       this.expireDate = expireDate;
    }
   
     @Id 
    
    @Column(name="session_key", unique=true, nullable=false, length=40)
    public String getSessionKey() {
        return this.sessionKey;
    }
    
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
    }
    
    @Column(name="session_data", nullable=false)
    public String getSessionData() {
        return this.sessionData;
    }
    
    public void setSessionData(String sessionData) {
        this.sessionData = sessionData;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expire_date", nullable=false, length=19)
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }




}


