package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShootingsAreacommand generated by hbm2java
 */
@Entity
@Table(name="shootings_areacommand"
    ,catalog="django_ois"
)
public class ShootingsAreacommand  implements java.io.Serializable {


     private Integer id;
     private String areaCommand;

    public ShootingsAreacommand() {
    }

    public ShootingsAreacommand(String areaCommand) {
       this.areaCommand = areaCommand;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="area_command", nullable=false)
    public String getAreaCommand() {
        return this.areaCommand;
    }
    
    public void setAreaCommand(String areaCommand) {
        this.areaCommand = areaCommand;
    }




}


