package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShootingsRank generated by hbm2java
 */
@Entity
@Table(name="shootings_rank"
    ,catalog="django_ois"
)
public class ShootingsRank  implements java.io.Serializable {


     private Integer id;
     private String rank;

    public ShootingsRank() {
    }

    public ShootingsRank(String rank) {
       this.rank = rank;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="rank", nullable=false)
    public String getRank() {
        return this.rank;
    }
    
    public void setRank(String rank) {
        this.rank = rank;
    }




}


