package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShootingsIncident generated by hbm2java
 */
@Entity
@Table(name="shootings_incident"
    ,catalog="django_ois"
)
public class ShootingsIncident  implements java.io.Serializable {


     private Integer id;
     private Date incidentDate;
     private String location;
     private String zip;
     private Integer areaCommandId;
     private Double latitude;
     private Double longitude;
     private Integer shotsFired;
     private Integer shotsToSuspect;
     private boolean closeRange;
     private boolean accidentalDischarge;
     private boolean officerInjury;
     private boolean physicalStruggle;
     private boolean suspectFired;
     private String inquestResult;
     private boolean inquestUnanimous;
     private Date inquestDate;
     private boolean footPursuit;
     private boolean carPursuit;
     private String incidentLocation;
     private String initialContact;
     private boolean fatalIncident;
     private String natureOfIncident;
     private String summaryOfIncident;
     private String notes;
     private String officerWeapon1;
     private String officerWeapon2;
     private String officerWeapon3;
     private String officerWeapon4;
     private String officerWeapon5;
     private String officerWeapon6;
     private String officerWeapon7;
     private String officerWeapon8;
     private String whereShot1;
     private String whereShot2;
     private String whereShot3;
     private String whereShot4;
     private String whereShot5;
     private String whereShot6;
     private String nonLethalForce1;
     private String nonLethalForce2;
     private String nonLethalForce3;
     private String nonLethalForce4;
     private String nonLethalForce5;
     private String nonLethalForce6;
     private String nonLethalForce7;
     private String nonLethalForce8;
     private String fatalIncidentType;
     private Integer shotsFiredByPolice;
     private Integer shotsHitSuspect;
     private Integer callTypeId;
     private boolean lawsuitFiled;
     private String editorialStatus;
     private boolean suicideByCop;
     private String suicideByCopNotes;
     private boolean nonPoliceWitnesses;
     private boolean privateSetting;
     private Date dateModified;

    public ShootingsIncident() {
    }

	
    public ShootingsIncident(Date incidentDate, String location, String zip, boolean closeRange, boolean accidentalDischarge, boolean officerInjury, boolean physicalStruggle, boolean suspectFired, String inquestResult, boolean inquestUnanimous, boolean footPursuit, boolean carPursuit, String incidentLocation, String initialContact, boolean fatalIncident, String natureOfIncident, String summaryOfIncident, String notes, String officerWeapon1, String officerWeapon2, String officerWeapon3, String officerWeapon4, String officerWeapon5, String officerWeapon6, String officerWeapon7, String officerWeapon8, String whereShot1, String whereShot2, String whereShot3, String whereShot4, String whereShot5, String whereShot6, String nonLethalForce1, String nonLethalForce2, String nonLethalForce3, String nonLethalForce4, String nonLethalForce5, String nonLethalForce6, String nonLethalForce7, String nonLethalForce8, String fatalIncidentType, boolean lawsuitFiled, String editorialStatus, boolean suicideByCop, String suicideByCopNotes, boolean nonPoliceWitnesses, boolean privateSetting, Date dateModified) {
        this.incidentDate = incidentDate;
        this.location = location;
        this.zip = zip;
        this.closeRange = closeRange;
        this.accidentalDischarge = accidentalDischarge;
        this.officerInjury = officerInjury;
        this.physicalStruggle = physicalStruggle;
        this.suspectFired = suspectFired;
        this.inquestResult = inquestResult;
        this.inquestUnanimous = inquestUnanimous;
        this.footPursuit = footPursuit;
        this.carPursuit = carPursuit;
        this.incidentLocation = incidentLocation;
        this.initialContact = initialContact;
        this.fatalIncident = fatalIncident;
        this.natureOfIncident = natureOfIncident;
        this.summaryOfIncident = summaryOfIncident;
        this.notes = notes;
        this.officerWeapon1 = officerWeapon1;
        this.officerWeapon2 = officerWeapon2;
        this.officerWeapon3 = officerWeapon3;
        this.officerWeapon4 = officerWeapon4;
        this.officerWeapon5 = officerWeapon5;
        this.officerWeapon6 = officerWeapon6;
        this.officerWeapon7 = officerWeapon7;
        this.officerWeapon8 = officerWeapon8;
        this.whereShot1 = whereShot1;
        this.whereShot2 = whereShot2;
        this.whereShot3 = whereShot3;
        this.whereShot4 = whereShot4;
        this.whereShot5 = whereShot5;
        this.whereShot6 = whereShot6;
        this.nonLethalForce1 = nonLethalForce1;
        this.nonLethalForce2 = nonLethalForce2;
        this.nonLethalForce3 = nonLethalForce3;
        this.nonLethalForce4 = nonLethalForce4;
        this.nonLethalForce5 = nonLethalForce5;
        this.nonLethalForce6 = nonLethalForce6;
        this.nonLethalForce7 = nonLethalForce7;
        this.nonLethalForce8 = nonLethalForce8;
        this.fatalIncidentType = fatalIncidentType;
        this.lawsuitFiled = lawsuitFiled;
        this.editorialStatus = editorialStatus;
        this.suicideByCop = suicideByCop;
        this.suicideByCopNotes = suicideByCopNotes;
        this.nonPoliceWitnesses = nonPoliceWitnesses;
        this.privateSetting = privateSetting;
        this.dateModified = dateModified;
    }
    public ShootingsIncident(Date incidentDate, String location, String zip, Integer areaCommandId, Double latitude, Double longitude, Integer shotsFired, Integer shotsToSuspect, boolean closeRange, boolean accidentalDischarge, boolean officerInjury, boolean physicalStruggle, boolean suspectFired, String inquestResult, boolean inquestUnanimous, Date inquestDate, boolean footPursuit, boolean carPursuit, String incidentLocation, String initialContact, boolean fatalIncident, String natureOfIncident, String summaryOfIncident, String notes, String officerWeapon1, String officerWeapon2, String officerWeapon3, String officerWeapon4, String officerWeapon5, String officerWeapon6, String officerWeapon7, String officerWeapon8, String whereShot1, String whereShot2, String whereShot3, String whereShot4, String whereShot5, String whereShot6, String nonLethalForce1, String nonLethalForce2, String nonLethalForce3, String nonLethalForce4, String nonLethalForce5, String nonLethalForce6, String nonLethalForce7, String nonLethalForce8, String fatalIncidentType, Integer shotsFiredByPolice, Integer shotsHitSuspect, Integer callTypeId, boolean lawsuitFiled, String editorialStatus, boolean suicideByCop, String suicideByCopNotes, boolean nonPoliceWitnesses, boolean privateSetting, Date dateModified) {
       this.incidentDate = incidentDate;
       this.location = location;
       this.zip = zip;
       this.areaCommandId = areaCommandId;
       this.latitude = latitude;
       this.longitude = longitude;
       this.shotsFired = shotsFired;
       this.shotsToSuspect = shotsToSuspect;
       this.closeRange = closeRange;
       this.accidentalDischarge = accidentalDischarge;
       this.officerInjury = officerInjury;
       this.physicalStruggle = physicalStruggle;
       this.suspectFired = suspectFired;
       this.inquestResult = inquestResult;
       this.inquestUnanimous = inquestUnanimous;
       this.inquestDate = inquestDate;
       this.footPursuit = footPursuit;
       this.carPursuit = carPursuit;
       this.incidentLocation = incidentLocation;
       this.initialContact = initialContact;
       this.fatalIncident = fatalIncident;
       this.natureOfIncident = natureOfIncident;
       this.summaryOfIncident = summaryOfIncident;
       this.notes = notes;
       this.officerWeapon1 = officerWeapon1;
       this.officerWeapon2 = officerWeapon2;
       this.officerWeapon3 = officerWeapon3;
       this.officerWeapon4 = officerWeapon4;
       this.officerWeapon5 = officerWeapon5;
       this.officerWeapon6 = officerWeapon6;
       this.officerWeapon7 = officerWeapon7;
       this.officerWeapon8 = officerWeapon8;
       this.whereShot1 = whereShot1;
       this.whereShot2 = whereShot2;
       this.whereShot3 = whereShot3;
       this.whereShot4 = whereShot4;
       this.whereShot5 = whereShot5;
       this.whereShot6 = whereShot6;
       this.nonLethalForce1 = nonLethalForce1;
       this.nonLethalForce2 = nonLethalForce2;
       this.nonLethalForce3 = nonLethalForce3;
       this.nonLethalForce4 = nonLethalForce4;
       this.nonLethalForce5 = nonLethalForce5;
       this.nonLethalForce6 = nonLethalForce6;
       this.nonLethalForce7 = nonLethalForce7;
       this.nonLethalForce8 = nonLethalForce8;
       this.fatalIncidentType = fatalIncidentType;
       this.shotsFiredByPolice = shotsFiredByPolice;
       this.shotsHitSuspect = shotsHitSuspect;
       this.callTypeId = callTypeId;
       this.lawsuitFiled = lawsuitFiled;
       this.editorialStatus = editorialStatus;
       this.suicideByCop = suicideByCop;
       this.suicideByCopNotes = suicideByCopNotes;
       this.nonPoliceWitnesses = nonPoliceWitnesses;
       this.privateSetting = privateSetting;
       this.dateModified = dateModified;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="incident_date", nullable=false, length=19)
    public Date getIncidentDate() {
        return this.incidentDate;
    }
    
    public void setIncidentDate(Date incidentDate) {
        this.incidentDate = incidentDate;
    }
    
    @Column(name="location", nullable=false)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    
    @Column(name="zip", nullable=false, length=10)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    
    @Column(name="area_command_id")
    public Integer getAreaCommandId() {
        return this.areaCommandId;
    }
    
    public void setAreaCommandId(Integer areaCommandId) {
        this.areaCommandId = areaCommandId;
    }
    
    @Column(name="latitude", precision=22, scale=0)
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    
    @Column(name="longitude", precision=22, scale=0)
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    
    @Column(name="shots_fired")
    public Integer getShotsFired() {
        return this.shotsFired;
    }
    
    public void setShotsFired(Integer shotsFired) {
        this.shotsFired = shotsFired;
    }
    
    @Column(name="shots_to_suspect")
    public Integer getShotsToSuspect() {
        return this.shotsToSuspect;
    }
    
    public void setShotsToSuspect(Integer shotsToSuspect) {
        this.shotsToSuspect = shotsToSuspect;
    }
    
    @Column(name="close_range", nullable=false)
    public boolean isCloseRange() {
        return this.closeRange;
    }
    
    public void setCloseRange(boolean closeRange) {
        this.closeRange = closeRange;
    }
    
    @Column(name="accidental_discharge", nullable=false)
    public boolean isAccidentalDischarge() {
        return this.accidentalDischarge;
    }
    
    public void setAccidentalDischarge(boolean accidentalDischarge) {
        this.accidentalDischarge = accidentalDischarge;
    }
    
    @Column(name="officer_injury", nullable=false)
    public boolean isOfficerInjury() {
        return this.officerInjury;
    }
    
    public void setOfficerInjury(boolean officerInjury) {
        this.officerInjury = officerInjury;
    }
    
    @Column(name="physical_struggle", nullable=false)
    public boolean isPhysicalStruggle() {
        return this.physicalStruggle;
    }
    
    public void setPhysicalStruggle(boolean physicalStruggle) {
        this.physicalStruggle = physicalStruggle;
    }
    
    @Column(name="suspect_fired", nullable=false)
    public boolean isSuspectFired() {
        return this.suspectFired;
    }
    
    public void setSuspectFired(boolean suspectFired) {
        this.suspectFired = suspectFired;
    }
    
    @Column(name="inquest_result", nullable=false, length=1)
    public String getInquestResult() {
        return this.inquestResult;
    }
    
    public void setInquestResult(String inquestResult) {
        this.inquestResult = inquestResult;
    }
    
    @Column(name="inquest_unanimous", nullable=false)
    public boolean isInquestUnanimous() {
        return this.inquestUnanimous;
    }
    
    public void setInquestUnanimous(boolean inquestUnanimous) {
        this.inquestUnanimous = inquestUnanimous;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="inquest_date", length=10)
    public Date getInquestDate() {
        return this.inquestDate;
    }
    
    public void setInquestDate(Date inquestDate) {
        this.inquestDate = inquestDate;
    }
    
    @Column(name="foot_pursuit", nullable=false)
    public boolean isFootPursuit() {
        return this.footPursuit;
    }
    
    public void setFootPursuit(boolean footPursuit) {
        this.footPursuit = footPursuit;
    }
    
    @Column(name="car_pursuit", nullable=false)
    public boolean isCarPursuit() {
        return this.carPursuit;
    }
    
    public void setCarPursuit(boolean carPursuit) {
        this.carPursuit = carPursuit;
    }
    
    @Column(name="incident_location", nullable=false, length=1)
    public String getIncidentLocation() {
        return this.incidentLocation;
    }
    
    public void setIncidentLocation(String incidentLocation) {
        this.incidentLocation = incidentLocation;
    }
    
    @Column(name="initial_contact", nullable=false, length=2)
    public String getInitialContact() {
        return this.initialContact;
    }
    
    public void setInitialContact(String initialContact) {
        this.initialContact = initialContact;
    }
    
    @Column(name="fatal_incident", nullable=false)
    public boolean isFatalIncident() {
        return this.fatalIncident;
    }
    
    public void setFatalIncident(boolean fatalIncident) {
        this.fatalIncident = fatalIncident;
    }
    
    @Column(name="nature_of_incident", nullable=false)
    public String getNatureOfIncident() {
        return this.natureOfIncident;
    }
    
    public void setNatureOfIncident(String natureOfIncident) {
        this.natureOfIncident = natureOfIncident;
    }
    
    @Column(name="summary_of_incident", nullable=false)
    public String getSummaryOfIncident() {
        return this.summaryOfIncident;
    }
    
    public void setSummaryOfIncident(String summaryOfIncident) {
        this.summaryOfIncident = summaryOfIncident;
    }
    
    @Column(name="notes", nullable=false)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    @Column(name="officer_weapon1", nullable=false)
    public String getOfficerWeapon1() {
        return this.officerWeapon1;
    }
    
    public void setOfficerWeapon1(String officerWeapon1) {
        this.officerWeapon1 = officerWeapon1;
    }
    
    @Column(name="officer_weapon2", nullable=false)
    public String getOfficerWeapon2() {
        return this.officerWeapon2;
    }
    
    public void setOfficerWeapon2(String officerWeapon2) {
        this.officerWeapon2 = officerWeapon2;
    }
    
    @Column(name="officer_weapon3", nullable=false)
    public String getOfficerWeapon3() {
        return this.officerWeapon3;
    }
    
    public void setOfficerWeapon3(String officerWeapon3) {
        this.officerWeapon3 = officerWeapon3;
    }
    
    @Column(name="officer_weapon4", nullable=false)
    public String getOfficerWeapon4() {
        return this.officerWeapon4;
    }
    
    public void setOfficerWeapon4(String officerWeapon4) {
        this.officerWeapon4 = officerWeapon4;
    }
    
    @Column(name="officer_weapon5", nullable=false)
    public String getOfficerWeapon5() {
        return this.officerWeapon5;
    }
    
    public void setOfficerWeapon5(String officerWeapon5) {
        this.officerWeapon5 = officerWeapon5;
    }
    
    @Column(name="officer_weapon6", nullable=false)
    public String getOfficerWeapon6() {
        return this.officerWeapon6;
    }
    
    public void setOfficerWeapon6(String officerWeapon6) {
        this.officerWeapon6 = officerWeapon6;
    }
    
    @Column(name="officer_weapon7", nullable=false)
    public String getOfficerWeapon7() {
        return this.officerWeapon7;
    }
    
    public void setOfficerWeapon7(String officerWeapon7) {
        this.officerWeapon7 = officerWeapon7;
    }
    
    @Column(name="officer_weapon8", nullable=false)
    public String getOfficerWeapon8() {
        return this.officerWeapon8;
    }
    
    public void setOfficerWeapon8(String officerWeapon8) {
        this.officerWeapon8 = officerWeapon8;
    }
    
    @Column(name="where_shot1", nullable=false)
    public String getWhereShot1() {
        return this.whereShot1;
    }
    
    public void setWhereShot1(String whereShot1) {
        this.whereShot1 = whereShot1;
    }
    
    @Column(name="where_shot2", nullable=false)
    public String getWhereShot2() {
        return this.whereShot2;
    }
    
    public void setWhereShot2(String whereShot2) {
        this.whereShot2 = whereShot2;
    }
    
    @Column(name="where_shot3", nullable=false)
    public String getWhereShot3() {
        return this.whereShot3;
    }
    
    public void setWhereShot3(String whereShot3) {
        this.whereShot3 = whereShot3;
    }
    
    @Column(name="where_shot4", nullable=false)
    public String getWhereShot4() {
        return this.whereShot4;
    }
    
    public void setWhereShot4(String whereShot4) {
        this.whereShot4 = whereShot4;
    }
    
    @Column(name="where_shot5", nullable=false)
    public String getWhereShot5() {
        return this.whereShot5;
    }
    
    public void setWhereShot5(String whereShot5) {
        this.whereShot5 = whereShot5;
    }
    
    @Column(name="where_shot6", nullable=false)
    public String getWhereShot6() {
        return this.whereShot6;
    }
    
    public void setWhereShot6(String whereShot6) {
        this.whereShot6 = whereShot6;
    }
    
    @Column(name="non_lethal_force1", nullable=false, length=2)
    public String getNonLethalForce1() {
        return this.nonLethalForce1;
    }
    
    public void setNonLethalForce1(String nonLethalForce1) {
        this.nonLethalForce1 = nonLethalForce1;
    }
    
    @Column(name="non_lethal_force2", nullable=false, length=2)
    public String getNonLethalForce2() {
        return this.nonLethalForce2;
    }
    
    public void setNonLethalForce2(String nonLethalForce2) {
        this.nonLethalForce2 = nonLethalForce2;
    }
    
    @Column(name="non_lethal_force3", nullable=false, length=2)
    public String getNonLethalForce3() {
        return this.nonLethalForce3;
    }
    
    public void setNonLethalForce3(String nonLethalForce3) {
        this.nonLethalForce3 = nonLethalForce3;
    }
    
    @Column(name="non_lethal_force4", nullable=false, length=2)
    public String getNonLethalForce4() {
        return this.nonLethalForce4;
    }
    
    public void setNonLethalForce4(String nonLethalForce4) {
        this.nonLethalForce4 = nonLethalForce4;
    }
    
    @Column(name="non_lethal_force5", nullable=false, length=2)
    public String getNonLethalForce5() {
        return this.nonLethalForce5;
    }
    
    public void setNonLethalForce5(String nonLethalForce5) {
        this.nonLethalForce5 = nonLethalForce5;
    }
    
    @Column(name="non_lethal_force6", nullable=false, length=2)
    public String getNonLethalForce6() {
        return this.nonLethalForce6;
    }
    
    public void setNonLethalForce6(String nonLethalForce6) {
        this.nonLethalForce6 = nonLethalForce6;
    }
    
    @Column(name="non_lethal_force7", nullable=false, length=2)
    public String getNonLethalForce7() {
        return this.nonLethalForce7;
    }
    
    public void setNonLethalForce7(String nonLethalForce7) {
        this.nonLethalForce7 = nonLethalForce7;
    }
    
    @Column(name="non_lethal_force8", nullable=false, length=2)
    public String getNonLethalForce8() {
        return this.nonLethalForce8;
    }
    
    public void setNonLethalForce8(String nonLethalForce8) {
        this.nonLethalForce8 = nonLethalForce8;
    }
    
    @Column(name="fatal_incident_type", nullable=false, length=1)
    public String getFatalIncidentType() {
        return this.fatalIncidentType;
    }
    
    public void setFatalIncidentType(String fatalIncidentType) {
        this.fatalIncidentType = fatalIncidentType;
    }
    
    @Column(name="shots_fired_by_police")
    public Integer getShotsFiredByPolice() {
        return this.shotsFiredByPolice;
    }
    
    public void setShotsFiredByPolice(Integer shotsFiredByPolice) {
        this.shotsFiredByPolice = shotsFiredByPolice;
    }
    
    @Column(name="shots_hit_suspect")
    public Integer getShotsHitSuspect() {
        return this.shotsHitSuspect;
    }
    
    public void setShotsHitSuspect(Integer shotsHitSuspect) {
        this.shotsHitSuspect = shotsHitSuspect;
    }
    
    @Column(name="call_type_id")
    public Integer getCallTypeId() {
        return this.callTypeId;
    }
    
    public void setCallTypeId(Integer callTypeId) {
        this.callTypeId = callTypeId;
    }
    
    @Column(name="lawsuit_filed", nullable=false)
    public boolean isLawsuitFiled() {
        return this.lawsuitFiled;
    }
    
    public void setLawsuitFiled(boolean lawsuitFiled) {
        this.lawsuitFiled = lawsuitFiled;
    }
    
    @Column(name="editorial_status", nullable=false, length=1)
    public String getEditorialStatus() {
        return this.editorialStatus;
    }
    
    public void setEditorialStatus(String editorialStatus) {
        this.editorialStatus = editorialStatus;
    }
    
    @Column(name="suicide_by_cop", nullable=false)
    public boolean isSuicideByCop() {
        return this.suicideByCop;
    }
    
    public void setSuicideByCop(boolean suicideByCop) {
        this.suicideByCop = suicideByCop;
    }
    
    @Column(name="suicide_by_cop_notes", nullable=false)
    public String getSuicideByCopNotes() {
        return this.suicideByCopNotes;
    }
    
    public void setSuicideByCopNotes(String suicideByCopNotes) {
        this.suicideByCopNotes = suicideByCopNotes;
    }
    
    @Column(name="non_police_witnesses", nullable=false)
    public boolean isNonPoliceWitnesses() {
        return this.nonPoliceWitnesses;
    }
    
    public void setNonPoliceWitnesses(boolean nonPoliceWitnesses) {
        this.nonPoliceWitnesses = nonPoliceWitnesses;
    }
    
    @Column(name="private_setting", nullable=false)
    public boolean isPrivateSetting() {
        return this.privateSetting;
    }
    
    public void setPrivateSetting(boolean privateSetting) {
        this.privateSetting = privateSetting;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_modified", nullable=false, length=19)
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }




}


