package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShootingsCrime generated by hbm2java
 */
@Entity
@Table(name="shootings_crime"
    ,catalog="django_ois"
)
public class ShootingsCrime  implements java.io.Serializable {


     private Integer id;
     private String crime;

    public ShootingsCrime() {
    }

    public ShootingsCrime(String crime) {
       this.crime = crime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="crime", nullable=false)
    public String getCrime() {
        return this.crime;
    }
    
    public void setCrime(String crime) {
        this.crime = crime;
    }




}


