package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ZAuditChange generated by hbm2java
 */
@Entity
@Table(name="z_AuditChange"
    ,catalog="django_ois"
)
public class ZAuditChange  implements java.io.Serializable {


     private Integer acid;
     private Date acdate;
     private String acsource;
     private String acaction;

    public ZAuditChange() {
    }

	
    public ZAuditChange(Date acdate, String acaction) {
        this.acdate = acdate;
        this.acaction = acaction;
    }
    public ZAuditChange(Date acdate, String acsource, String acaction) {
       this.acdate = acdate;
       this.acsource = acsource;
       this.acaction = acaction;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ACId", unique=true, nullable=false)
    public Integer getAcid() {
        return this.acid;
    }
    
    public void setAcid(Integer acid) {
        this.acid = acid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACDate", nullable=false, length=19)
    public Date getAcdate() {
        return this.acdate;
    }
    
    public void setAcdate(Date acdate) {
        this.acdate = acdate;
    }
    
    @Column(name="ACSource", length=45)
    public String getAcsource() {
        return this.acsource;
    }
    
    public void setAcsource(String acsource) {
        this.acsource = acsource;
    }
    
    @Column(name="ACAction", nullable=false, length=10)
    public String getAcaction() {
        return this.acaction;
    }
    
    public void setAcaction(String acaction) {
        this.acaction = acaction;
    }




}


