package com.sm.mavensqlutil.entity;
// Generated Jan 10, 2012 10:05:40 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ZTestTriggerSource generated by hbm2java
 */
@Entity
@Table(name="z_TestTriggerSource"
    ,catalog="django_ois"
)
public class ZTestTriggerSource  implements java.io.Serializable {


     private Integer ttsid;
     private String ttsnameFirst;
     private String ttsnameLast;
     private String ttscoD;

    public ZTestTriggerSource() {
    }

    public ZTestTriggerSource(String ttsnameFirst, String ttsnameLast, String ttscoD) {
       this.ttsnameFirst = ttsnameFirst;
       this.ttsnameLast = ttsnameLast;
       this.ttscoD = ttscoD;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="TTSId", unique=true, nullable=false)
    public Integer getTtsid() {
        return this.ttsid;
    }
    
    public void setTtsid(Integer ttsid) {
        this.ttsid = ttsid;
    }
    
    @Column(name="TTSNameFirst", nullable=false, length=45)
    public String getTtsnameFirst() {
        return this.ttsnameFirst;
    }
    
    public void setTtsnameFirst(String ttsnameFirst) {
        this.ttsnameFirst = ttsnameFirst;
    }
    
    @Column(name="TTSNameLast", nullable=false, length=45)
    public String getTtsnameLast() {
        return this.ttsnameLast;
    }
    
    public void setTtsnameLast(String ttsnameLast) {
        this.ttsnameLast = ttsnameLast;
    }
    
    @Column(name="TTSCoD", nullable=false, length=45)
    public String getTtscoD() {
        return this.ttscoD;
    }
    
    public void setTtscoD(String ttscoD) {
        this.ttscoD = ttscoD;
    }




}


